### PR TITLE
Add missing api.rst; call sphinx-apidoc in RTD pre-build

### PR DESCRIPTION
**Pull request by cmarqu**
Before merging, please enable PR builds as described in https://docs.readthedocs.io/en/stable/guides/pull-requests.html,
then let me try another push.

### CODE REVIEW

**Comment by weiwei** [comment]
Hi @cmarqu PR builds is enabled. You can continue now.

**Comment by cmarqu** [comment]
Doesn't work...
Do you see an RTD webhook configured under https://github.com/weiwei/junitparser/settings/hooks ?
https://docs.readthedocs.io/en/stable/guides/pull-requests.html#troubleshooting also has some tips.

**Comment by weiwei** [comment]
Yes @cmarqu the config should be correct. I'll merge this first to see if it gets triggered.

**Review by weiwei — APPROVED** [review]

**Comment by weiwei** [comment]
OK webhooks by default are triggered by pushes not PRs. It did run after I merge, but failed on the newly added command: https://readthedocs.org/projects/junitparser/builds/23025833/

**Comment by weiwei** [comment]
@cmarqu  I think I've properly enabled webhook for PR now. You can test it out.
image

**Pull request merged**
