### PR TITLE
Fix path for RTD sphinx-apidoc pre_build step

### PR DESCRIPTION
**Pull request by cmarqu**
Another try.

### CODE REVIEW

**Comment by weiwei** [comment]
It still doesn't build on PRs...But I think it is working! https://readthedocs.org/projects/junitparser/builds/23034423/

**Comment by cmarqu** [comment]
Yes, it shows the API now: https://junitparser.readthedocs.io/en/latest/inheritance_diagram.html
The TOC on the left still doesn't look like when I build it locally, but I guess it's fine for now.

**Comment by weiwei** [comment]
Thanks for all the work @cmarqu. Have a wonderful weekend!

**Comment by cmarqu** [comment]
Same to you, and thanks for the useful package!

**Pull request merged**
