### PR TITLE
Fix RTD rendering of inheritance diagram; show API docs

### PR DESCRIPTION
**Pull request by cmarqu**

### CODE REVIEW

**Review by weiwei — APPROVED** [review]
Hi @cmarqu Thanks again for the PR!

**Review by weiwei — APPROVED** [review]
Hi @cmarqu Thanks again for the PR!

**Review by weiwei — APPROVED** [review]
Hi @cmarqu Thanks again for the PR!

**Comment by weiwei** [comment]
Wow look what happens during a network glitch

**Comment by cmarqu** [comment]
Argh, something is still not right. I'll prepare another PR in a few hours.

I'm kinda flying blind because I don't see doc builds for PRs - did you do the settings from #113 in the RTD GUI?

**Pull request merged**
